version: "3"
services:
  pg_master:
    build: ./master
    volumes:
      - pg_master_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ORD@@hms58770
      - POSTGRES_DB=hms_prod
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=rep_ORD@@hms58770
    networks:
      default:
        aliases:
          - pg_cluster
    ports:
      - "8001:5432"
  pg_slave:
    build: ./slave
    volumes:
      - pg_slave_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ORD@@hms58770
      - POSTGRES_DB=hms_prod
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=rep_ORD@@hms58770
    networks:
      default:
        aliases:
          - pg_cluster
    ports:
      - "8002:5432"
volumes:
  pg_master_data:
  pg_slave_data: